export interface AllergenInfo {
  code: number;
  name: string;
  shortName: string;
  category: string;
  badgeBg: string;
  badgeText: string;
  iconName: string;
}

export const ALLERGEN_DICT: Record<number, AllergenInfo> = {
  1: {
    code: 1,
    name: '난류 (달걀/계란)',
    shortName: '난류',
    category: '가금류/알',
    badgeBg: 'bg-amber-100 dark:bg-amber-950/60',
    badgeText: 'text-amber-800 dark:text-amber-300',
    iconName: 'Egg',
  },
  2: {
    code: 2,
    name: '우유 (유제품)',
    shortName: '우유',
    category: '유제품',
    badgeBg: 'bg-blue-100 dark:bg-blue-950/60',
    badgeText: 'text-blue-800 dark:text-blue-300',
    iconName: 'Milk',
  },
  3: {
    code: 3,
    name: '메밀',
    shortName: '메밀',
    category: '곡류',
    badgeBg: 'bg-stone-100 dark:bg-stone-800',
    badgeText: 'text-stone-800 dark:text-stone-300',
    iconName: 'Wheat',
  },
  4: {
    code: 4,
    name: '땅콩',
    shortName: '땅콩',
    category: '견과류',
    badgeBg: 'bg-yellow-100 dark:bg-yellow-950/60',
    badgeText: 'text-yellow-800 dark:text-yellow-300',
    iconName: 'Nut',
  },
  5: {
    code: 5,
    name: '대두 (콩)',
    shortName: '대두(콩)',
    category: '콩류',
    badgeBg: 'bg-emerald-100 dark:bg-emerald-950/60',
    badgeText: 'text-emerald-800 dark:text-emerald-300',
    iconName: 'Bean',
  },
  6: {
    code: 6,
    name: '밀 (밀가루)',
    shortName: '밀',
    category: '곡류',
    badgeBg: 'bg-orange-100 dark:bg-orange-950/60',
    badgeText: 'text-orange-800 dark:text-orange-300',
    iconName: 'Wheat',
  },
  7: {
    code: 7,
    name: '고등어',
    shortName: '고등어',
    category: '생선류',
    badgeBg: 'bg-cyan-100 dark:bg-cyan-950/60',
    badgeText: 'text-cyan-800 dark:text-cyan-300',
    iconName: 'Fish',
  },
  8: {
    code: 8,
    name: '게',
    shortName: '게',
    category: '갑각류',
    badgeBg: 'bg-rose-100 dark:bg-rose-950/60',
    badgeText: 'text-rose-800 dark:text-rose-300',
    iconName: 'Shellfish',
  },
  9: {
    code: 9,
    name: '새우',
    shortName: '새우',
    category: '갑각류',
    badgeBg: 'bg-red-100 dark:bg-red-950/60',
    badgeText: 'text-red-800 dark:text-red-300',
    iconName: 'Shrimp',
  },
  10: {
    code: 10,
    name: '돼지고기',
    shortName: '돼지고기',
    category: '육류',
    badgeBg: 'bg-pink-100 dark:bg-pink-950/60',
    badgeText: 'text-pink-800 dark:text-pink-300',
    iconName: 'Beef',
  },
  11: {
    code: 11,
    name: '복숭아',
    shortName: '복숭아',
    category: '과일류',
    badgeBg: 'bg-rose-100 dark:bg-rose-950/60',
    badgeText: 'text-rose-800 dark:text-rose-300',
    iconName: 'Apple',
  },
  12: {
    code: 12,
    name: '토마토',
    shortName: '토마토',
    category: '채소/과채류',
    badgeBg: 'bg-red-100 dark:bg-red-950/60',
    badgeText: 'text-red-800 dark:text-red-300',
    iconName: 'Cherry',
  },
  13: {
    code: 13,
    name: '아황산류 (보존료)',
    shortName: '아황산류',
    category: '첨가물',
    badgeBg: 'bg-violet-100 dark:bg-violet-950/60',
    badgeText: 'text-violet-800 dark:text-violet-300',
    iconName: 'FlaskConical',
  },
  14: {
    code: 14,
    name: '호두',
    shortName: '호두',
    category: '견과류',
    badgeBg: 'bg-amber-100 dark:bg-amber-950/60',
    badgeText: 'text-amber-800 dark:text-amber-300',
    iconName: 'Nut',
  },
  15: {
    code: 15,
    name: '닭고기',
    shortName: '닭고기',
    category: '가금류',
    badgeBg: 'bg-orange-100 dark:bg-orange-950/60',
    badgeText: 'text-orange-800 dark:text-orange-300',
    iconName: 'Drumstick',
  },
  16: {
    code: 16,
    name: '쇠고기 (소고기)',
    shortName: '쇠고기',
    category: '육류',
    badgeBg: 'bg-red-100 dark:bg-red-950/60',
    badgeText: 'text-red-800 dark:text-red-300',
    iconName: 'Beef',
  },
  17: {
    code: 17,
    name: '오징어',
    shortName: '오징어',
    category: '연체류',
    badgeBg: 'bg-indigo-100 dark:bg-indigo-950/60',
    badgeText: 'text-indigo-800 dark:text-indigo-300',
    iconName: 'Fish',
  },
  18: {
    code: 18,
    name: '조개류 (굴/전복/홍합 등)',
    shortName: '조개류',
    category: '패류',
    badgeBg: 'bg-teal-100 dark:bg-teal-950/60',
    badgeText: 'text-teal-800 dark:text-teal-300',
    iconName: 'Shellfish',
  },
  19: {
    code: 19,
    name: '잣',
    shortName: '잣',
    category: '견과류',
    badgeBg: 'bg-yellow-100 dark:bg-yellow-950/60',
    badgeText: 'text-yellow-800 dark:text-yellow-300',
    iconName: 'Nut',
  },
};

export const ALL_ALLERGEN_LIST = Object.values(ALLERGEN_DICT);
